
= Images
If you want to link to an image:

1. Put it in `<topic_dir>/images`
2. In the topic document, use this format to link to an image:

----
image::<name_of_image>[image]
----

You only need to specify `<name_of_image>`.
The build mechanism automatically specifies the file path.

=== AsciiDoctor diagram extension
AsciiDoctor provides a set of
http://asciidoctor.org/docs/asciidoctor-diagram/[extensions to embed diagrams]
written using
http://plantuml.sourceforge.net/[PlantUML],
http://www.graphviz.org/[Graphviz],
http://ditaa.sourceforge.net/[ditaa],
or https://github.com/christiangoltz/shaape[Shaape]
syntax inside your AsciiDoc documents.
The diagram extension generates an SVG, PNG, or TXT file
from the source text.
The image file that's generated then gets inserted into the rendered document.

[IMPORTANT]
====
The AsciiDoctor diagram extension serves a starting point
for including images in the documentation.
In most cases these images will be professionally enhanced
to meet our internal standards and guidelines.
====

See the
http://asciidoctor.org/docs/asciidoctor-diagram/[AsciiDoctor diagram extension]
documentation for instructions on how to install and use it.


We will mostly use the `ditaa` block.
The `png` file from the `ditaa` block is generated in the same directory
as the source file with a checksum as the filename.
However, you can specify the path of the generated `png` file
with the second attribute in the `ditaa` block.

For example, in our case we would want our images
in the *topic_dir/_images_* folder of the main topic directory:

----
....
[ditaa, "images/name_of_image"]
....
----
