

:experimental:
== AsciiDoc Markup Quick Reference

|===
|Convention|Markup|Example rendered output

|Anchor
a| for simple anchors:
$$[[anchor_name]]$$

for anchors in modular content to avoid clashes:
$$[#anchor_name_{parameter}]$$

a| for simple anchors:

[[anchor_name]] Section Header

for anchors in modular content to avoid clashes:

[#anchor_name_{parameter}] Section Header

|Application name
a|No special markup
a| The foo application.

|Code blocks
a|
....
Use the following syntax for the `oc` command:
[subs="+quotes,attributes"]
----
$ *oc <action> <object_type> <object_name_or_id>*
----
....

a|Use the following syntax for the `oc` command:
[subs="+quotes,attributes"]
----
$ *oc <action> <object_type> <object_name_or_id>*
----

|Code - inline
a|
a|

|Command block
a|
a|

|Command - inline
a|$$[command]*$$
a|use [command]*yum to install new packages.

|Emphasis for a term
a|$$_emphasis_$$
a|Use _this_ approach.

|File names or directory paths
a|$$`filename`$$

$$`directory`$$
a|Edit the `kubeconfig` file as required and save your changes.

The `express.conf` configuration file is located in the `/usr/share/` directory.

|GUI Elements
a|GUI $$*text*$$

GUI $$btn:[button]$$

GUI $$menu:File[Menu Item>Another]$$

NOTE: For button and menu, add the $$:experimental:$$ attribute to your files.
a|The web browser displays *404* for an unreachable URL.

Press  btn:[back] to return to a prior page.

Navigate to menu:File[Open>file] to open your work.

|Images
a|Images inline:

Image block:


a|Images inline:

Image block:

|Inline commands, operations, and user input
a|$$`oc get`$$

$$`GET`$$

$$Answer by typing `Yes` or `No` when prompted.$$
a|Use the `oc get` command to get a list of services that are currently defined.

The `GET` operation can be used to do something.

Answer by typing `Yes` or `No` when prompted.
|Lists
a|.Ordered list
----
. First item
. Second item
. Third item
----

NOTE: Do not put steps in bold.

.Unordered list
----
* This
* That
* The other
----

.Definition or labeled list
----
Term A:: description
Term A:: description
----

a|.Ordered list

. First item
. Second item
. Third item

.Unordered list

* This
* That
* The other

.Definition  or labeled list
Term A:: description
Term B:: description

|Literal value
a|$$`true`$$
a|Set the value of the `enabled` attribute to `true`.

|Package
a|Install the $$[package]*foo$$ package.
a|Install the [package]*foo package.

|Product name
a|No special markup
a|Red Hat Enterprise Linux

|Reference to Red Hat guides
a|\link:__LINK_URL__[\_Guide Title_]
a|See the JBoss EAP link:https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/getting_started_guide/[_Getting Started Guide_] for more information.

|System or software variable to be replaced by the user
a|$$`<project>`$$

$$`<deployment>`$$

$$`package_name`$$

a|
Use the following command to roll back a deployment, specifying the deployment name: `oc rollback <deployment>`

Install the `gimp` package.

|System or software configuration parameter or environment variable
a|$$`*ENVIRONMENT_VARIABLE*`$$

$$`*PARAMETER*`$$

a|Use the `*IP_ADDRESS*` environment variable for the server IP address.

The `*MAX_PODS*` parameter limits the number of pods you can have.

|System term, daemon, service, or software package
a|$$*system item*$$

$$*daemon*$$

$$*service*$$

$$Select *menu:File[Save]*$$

a|*HTTPD*

*NetworkManager*

Select *File ▸ Save*
|===
